apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../keycloak/keycloak-ingress
patchesStrategicMerge:
  - |-
    apiVersion: install.istio.io/v1alpha1
    kind: IstioOperator
    metadata:
      name: keycloak-ingressgateway
      namespace: istio-system
    spec:
      components:
        ingressGateways:
        - name: keycloak-ingressgateway
          namespace: istio-system
          enabled: true
          label:
            app: keycloak-ingressgateway
            istio: ingressgateway
          k8s:
            service:
              type: LoadBalancer
              loadBalancerIP: 172.28.0.4
