chains:
  foo:
    callback_uri: https://foo.bigbang.dev/login
    client_id: foo
    client_secret: 2mMLbBB2V7ngoGOY0N6fP0i47f68eDNP
    logout_path: /logout
    match:
      header: :authority
      prefix: foo.bigbang.dev
global:
  authorization_uri: https://###ZARF_VAR_KEYCLOAK_BASE_DOMAIN###/auth/realms/###ZARF_VAR_KEYCLOAK_REALM###/protocol/openid-connect/auth
  certificate_authority: |
    ###ZARF_VAR_CA_FILE###
  jwks_uri: https://###ZARF_VAR_KEYCLOAK_BASE_DOMAIN###/auth/realms/###ZARF_VAR_KEYCLOAK_REALM###/protocol/openid-connect/certs
  logout_redirect_uri: https://###ZARF_VAR_KEYCLOAK_BASE_DOMAIN###/auth/realms/###ZARF_VAR_KEYCLOAK_REALM###/protocol/openid-connect/logout
  oidc:
    host: ###ZARF_VAR_KEYCLOAK_BASE_DOMAIN###
    realm: ###ZARF_VAR_KEYCLOAK_REALM###
  token_uri: https://###ZARF_VAR_KEYCLOAK_BASE_DOMAIN###/auth/realms/###ZARF_VAR_KEYCLOAK_REALM###/protocol/openid-connect/token
image:
  pullPolicy: IfNotPresent
imagePullSecrets:
- name: private-registry
issuer_uri: https://###ZARF_VAR_KEYCLOAK_BASE_DOMAIN###/auth/realms/###ZARF_VAR_KEYCLOAK_REALM###
monitoring:
  enabled: false
networkPolicies:
  enabled: false
  ingressLabels:
    app: null
    istio: null
openshift: false
podAnnotations:
  bigbang.dev/istioVersion: 1.17.2
