name: Test UDS SSO Upgrade 

on:
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  test-clean-install:
    runs-on: ubuntu-latest

    steps:

      - name: Fail if Draft PR
        if: github.event.pull_request.draft == true
        run: exit 1

      - uses: actions/checkout@v4

      - uses: ./.github/actions/create-zarf-package
        with:
          username: ${{ secrets.REGISTRY1_USERNAME }}
          password: ${{ secrets.REGISTRY1_PASSWORD }}
          working-dir: sso
          download-init-package: true

      - name: Create k3d cluster
        id: create-cluster
        # renovate: datasource=github-tags depName=defenseunicorns/uds-aws-ci-k3d versioning=semver
        uses: defenseunicorns/uds-aws-ci-k3d@v0.0.3
        with:
          cluster-action: create
          aws-assume-role: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME }}
          aws-region: us-west-2

      - name: Install uds-cli
        uses: supplypike/setup-bin@v3
        with:
          # renovate: uds-cli-uri datasource=github-tags depName=defenseunicorns/uds-cli
          uri: 'https://github.com/defenseunicorns/uds-cli/releases/download/v0.0.5-alpha/uds-cli_v0.0.5-alpha_Linux_amd64 '
          name: 'uds'
          # renovate: datasource=github-tags depName=defenseunicorns/uds-cli versioning=semver
          version: 'v0.0.5-alpha'

      # Build Env Setup Bundle (Zarf, Metallb, Dubbd, IDAM, Source SSO, Published SSO)
      - name: Build CI Upgrade Test for Published SSO
        run: make build/all-ci

      # Deploy SSO Test Setup Bundle 
      - name: Deploy CI Upgrade Test Published SSO
        run: make deploy/ci-upgrade-sso-published

      # Deploy Latest Published SSO 
      - name: Deploy CI Upgrade Test Source SSO
        run: make deploy/ci-upgrade-sso-source

      - name: Teardown k3d cluster
        if: always()
        # renovate: datasource=github-tags depName=defenseunicorns/uds-aws-ci-k3d versioning=semver
        uses: defenseunicorns/uds-aws-ci-k3d@v0.0.3
        with:
          cluster-action: destroy